version: 0.2

phases:
  install:
    runtime-versions:
      terraform: 1.5 # Ensure this matches the Terraform version in use
    commands:
      - echo "Installing dependencies..."
      - yum install -y unzip
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - sudo ./aws/install
      - terraform --version
      - aws --version

  pre_build:
    commands:
      - echo "Setting up the Terraform backend..."
      - terraform init
      - terraform validate

  build:
    commands:
      - echo "Applying Terraform configuration..."
      - terraform apply -auto-approve

  post_build:
    commands:
      - echo "Terraform apply completed."
      - terraform output -json > build_output.json
      - echo "Build output saved."

artifacts:
  files:
    - build_output.json
  discard-paths: no
  base-directory: .
